pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
		maven {
			url = "https://maven.kikugie.dev/snapshots"
			name = "KikuGie Snapshots"
		}
	}
}

plugins {
	id("dev.kikugie.stonecutter").version "0.9.6"
}

stonecutter {
	centralScript = "build.gradle"
	create(rootProject) {

		versions("26.1", "26.2", "26.3")
		vcsVersion = "26.1"
	}
}
// Should match your modid
rootProject.name = 'tilted'
